- name: "Install system tools and environment"
  hosts: 'all'
  gather_facts: false
  remote_user: startx
  become_method: sudo
  become: yes
  tasks:
  - name: Update installed packages
    shell: yum update -y
    ignore_errors: yes
  - name: Ensure basic tools are presents
    package:
      name:
        - bash-completion
        - git
        - curl
        - wget
        - epel-release
      state: present
  - name: Clean package cache
    shell: yum clean all
    ignore_errors: yes