- name: "Install docker tools and environment"
  hosts: 'all'
  gather_facts: true
  remote_user: startx
  become_method: sudo
  become: yes
  vars:
    pip_install_packages:
      - name: docker
    docker_edition: 'ce'
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: true
    docker_compose_version: "1.22.0"
    docker_users:
      - "{{ user_name }}"
  tasks:
  - name: Ensure geerlingguy.pip role is installed
    include_role: 
      name: geerlingguy.pip
  - name: Ensure geerlingguy.docker role is installed
    include_role: 
      name: geerlingguy.docker
  - name: Ensure docker service is running
    systemd:
      name: docker
      state: started