- name: "Install docker tools and environment"
  hosts: 'all'
  gather_facts: false
  remote_user: startx
  become_method: sudo
  become: yes
  tasks:
  - name: Update installed packages
    shell: yum update -y
  - name: Ensure docker tools are presents
    yum:
      name:
        - docker
      state: present
  - name: Clean package cache
    shell: yum clean all