- name: "Post-Install docker tools and environment"
  hosts: 'all'
  gather_facts: false
  remote_user: startx
  become_method: sudo
  become: yes
  tasks:
  - name: Remove containers-engines in /root
    file:
      path: /root/containers-engines
      state: absent