- name: "Pre-Install docker Enterprise tools and environment"
  hosts: 'all'
  gather_facts: false
  tasks:
  - name: Install roles from Ansible Galaxy
    command: ansible-galaxy install {{ item }}
    with_items:
      - geerlingguy.pip
      - geerlingguy.docker