- name: "Pre-Install S2I tools and environment"
  hosts: 'all'
  gather_facts: false
  vars:
    pip_install_packages:
      - name: docker
    docker_edition: 'ce'
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: true
    docker_compose_version: "1.22.0"
    docker_users:
      - "{{ user_name }}"
  tasks:
  - name: Install roles from Ansible Galaxy
    command: ansible-galaxy install {{ item }}
    with_items:
      - ikke_t.podman_container_systemd
      - geerlingguy.pip
      - geerlingguy.docker
  - name: Ensure geerlingguy.pip role is installed
    include_role: 
      name: geerlingguy.pip
  - name: Execute geerlingguy role's
    include_role: 
      name: "{{ item }}"
    with_items:
      - geerlingguy.pip
      - geerlingguy.docker
  - name: Ensure S2I runtime packages are installed
    package:
      name: 
      - podman
      - docker-{{ docker_edition }}
      - skopeo
      state: present
  - name: Ensure docker service is running
    systemd:
      name: docker
      state: started