- name: "Install podman tools and environment"
  hosts: 'all'
  gather_facts: true
  remote_user: startx
  become_method: sudo
  become: yes
  tasks:
  - name: ensure podman is installed
    package:
      name: podman
      state: installed