- name: "Uninstall podman tools and environment"
  hosts: 'all'
  gather_facts: true
  remote_user: startx
  become_method: sudo
  become: yes
  tasks:
  - name: Uninstall roles from Ansible Galaxy
    command: ansible-galaxy uninstall {{ item }}
    with_items:
      - ikke_t.podman_container_systemd
  - name: ensure podman is removed
    package:
      name: podman
      state: absent